# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LEOCHARRE-Class
version:      1.05
version_from: lib/LEOCHARRE/Class.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
