# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LEOCHARRE-Class
version:      1.12
version_from: lib/LEOCHARRE/Class/Accessors.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    LEOCHARRE::DEBUG:              1.06
    Test::Simple:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
